# -*- coding: utf-8 -*-
"""graphcolouring.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HtibJ3ZJQrY0TgXLXiZQ-2IkgDOEJxEy
"""

def is_safe(v, graph, color, c):
    for i in range(len(graph)):
        if graph[v][i] == 1 and color[i] == c:
            return False
    return True

def graph_coloring_util(graph, m, color, v):
    if v == len(graph):
        return True
    for c in range(1, m + 1):
        if is_safe(v, graph, color, c):
            color[v] = c
            if graph_coloring_util(graph, m, color, v + 1):
                return True
            color[v] = 0
    return False

def graph_coloring(graph, m, vertices):
    color = [0] * len(graph)
    if not graph_coloring_util(graph, m, color, 0):
        print("Solution does not exist")
        return
    print("Assigned Colours:")
    for i in range(len(vertices)):
        print(f"{vertices[i]} -> Colour {color[i]}")

vertices = ['A', 'B', 'C', 'D', 'E']
graph = [
    [0, 1, 1, 1, 0],
    [1, 0, 1, 0, 1],
    [1, 1, 0, 1, 1],
    [1, 0, 1, 0, 1],
    [0, 1, 1, 1, 0]
]
m = 3

graph_coloring(graph, m, vertices)

