# -*- coding: utf-8 -*-
"""Hamiltonian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1edR2JTK1WY5gYFJS_gI8giVDxsRU0E3v
"""

def is_safe(v, graph, path, pos):
    if graph[path[pos - 1]][v] == 0:
        return False
    if v in path:
        return False
    return True

def hamiltonian_cycle_util(graph, path, pos):
    if pos == len(graph):
        return graph[path[pos - 1]][path[0]] == 1
    for v in range(1, len(graph)):
        if is_safe(v, graph, path, pos):
            path[pos] = v
            if hamiltonian_cycle_util(graph, path, pos + 1):
                return True
            path[pos] = -1
    return False

def hamiltonian_cycle(graph, vertices):
    path = [-1] * len(graph)
    path[0] = 0
    if not hamiltonian_cycle_util(graph, path, 1):
        print("No safe route exists ")
        return
    print("This is the safest route:")
    for vertex in path:
        print(vertices[vertex], end=" -> ")
    print(vertices[path[0]])

vertices1 = ['A', 'B', 'C', 'D', 'E']
graph1 = [
    [0, 1, 1, 0, 1],
    [1, 0, 1, 1, 0],
    [1, 1, 0, 1, 0],
    [0, 1, 1, 0, 1],
    [1, 0, 0, 1, 0]
]

print("=== Graph 1 (A–E) ===")
hamiltonian_cycle(graph1, vertices1)

vertices2 = ['T', 'M', 'S', 'H', 'C']
graph2 = [
    [0, 1, 1, 0, 1],
    [1, 0, 1, 1, 0],
    [1, 1, 0, 1, 1],
    [0, 1, 1, 0, 1],
    [1, 0, 1, 1, 0]
]

print("\n=== Graph 2 (T–C) ===")
hamiltonian_cycle(graph2, vertices2)

